# DO NOT MODIFY THIS FILE, A SIMILAR FILE IS USED TO EVALUATE YOUR SUBMISSION, MODIFYING THIS FILE WILL RESULT IN ERRORS DURING EVALUATION

import numpy as np
import matplotlib.pyplot as plt
import random
from queue import PriorityQueue, Queue
import search_algorithms as sa

enable_GUI  = True

def generate_maze(map_size=20):
    maze = np.ones((map_size, map_size), dtype=int)  # Set all walls as obstacles initially
    costs = np.random.randint(1, 4, size=(map_size, map_size))  # Set all walls as obstacles initially
    
    # Create a clear area inside the walls
    maze[1:-1, 1:-1] = 0
    
    num_obstacles = 5  # Fixed number of obstacles
    obstacle_width = 1
    obstacle_length = 12
    
    for i in range(num_obstacles):
        x = (i + 1) * (map_size // (num_obstacles + 1))  # Equally spaced obstacles
        y = 0 if i % 2 == 0 else map_size - obstacle_length  # Alternate vertical walls
        
        maze[x:x + obstacle_width, y:y + obstacle_length] = 1  # Set horizontal obstacle
    
    def is_valid_start_goal(start, goal):
        return np.linalg.norm(np.array(start) - np.array(goal)) >= 20
    
    start = (np.random.randint(1, 5), np.random.randint(1, map_size - 1))
    goal = (np.random.randint(16, map_size - 1), np.random.randint(1, map_size - 1))
    while maze[start] == 1 or maze[goal] == 1 or start == goal or not is_valid_start_goal(start, goal):
        start = (np.random.randint(1, 5), np.random.randint(1, map_size - 1))
        goal = (np.random.randint(16, map_size - 1), np.random.randint(1, map_size - 1))

    return maze, costs, start, goal
  
def main():
    maze, costs, start, goal = generate_maze()
    print('Start = ', start );
    print('Goal = ', goal );

    bfs_path = sa.bfs(maze, start, goal)
    print('Path generated by yor BFS aglorithm is:', bfs_path)
    
    dfs_path = sa.dfs(maze, start, goal)
    print('Path generated by yor DFS aglorithm is:', dfs_path)

    ucs_path= sa.ucs(maze, costs, start, goal)
    print('Path generated by yor UCS aglorithm is:', ucs_path)
    
    if enable_GUI == True:
        fig, axes = plt.subplots(1, 3, figsize=(18, 6))
        titles = ["BFS Maze Solution", "DFS Maze Solution", "UCS Maze Solution"]
        paths = [bfs_path, dfs_path, ucs_path]
        
        for i, (path, ax) in enumerate(zip(paths, axes)):
            ax.imshow(maze, cmap='gray_r')
            ax.scatter(start[1], start[0], color='blue', s=50, label='Start')
            ax.scatter(goal[1], goal[0], color='red', s=50, label='Goal')
            if path:
                px, py = zip(*path)
                ax.plot(py, px, color='red', linewidth=2)
            ax.set_title(titles[i])
            ax.set_xlabel("Y-axis")
            ax.set_ylabel("X-axis")
            ax.legend()
            ax.set_xticks(np.arange(0, maze.shape[1], 1))
            ax.set_yticks(np.arange(0, maze.shape[0], 1))
            ax.grid(True, which='both', linestyle='--', linewidth=0.5)
        
        plt.show()

if __name__ == "__main__":
    main()